import { createElement } from "react";
import { docs } from "../../.source/server";
import { loader } from "fumadocs-core/source";
import { icons } from "lucide-react";

// `.source/server` is generated by `fumadocs-mdx` from source.config.ts.
// It lives at the project root, so this is a relative (not `@/`) import.
export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
  // Resolve the `icon:` frontmatter string to a lucide component. Without this,
  // Fumadocs has no way to turn "Album"/"Rocket"/… into an element and renders
  // the raw name as text in the sidebar.
  icon(icon) {
    // Object.hasOwn (not `in`) so only real lucide icon names match — a stray
    // frontmatter value like `toString` won't resolve to a prototype member.
    if (icon && Object.hasOwn(icons, icon)) {
      return createElement(icons[icon as keyof typeof icons]);
    }
    return undefined;
  },
});
