import { docs } from "../../.source/server";
import { loader } from "fumadocs-core/source";

// `.source/server` is generated by `fumadocs-mdx` from source.config.ts.
// It lives at the project root, so this is a relative (not `@/`) import.
export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
});
